#line 1 "metagrammar.yylex.c"

#line 3 "metagrammar.yylex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[260] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,   49,
       43,   43,   49,   49,   49,   11,   49,   15,   18,   17,
       49,   11,   11,   20,   19,   49,   50,   50,   50,   50,
       50,   25,   26,   31,   32,   33,   34,   35,   38,   39,
       38,   40,   50,   42,   29,   28,    5,    5,   43,    0,
       44,   47,    0,   36,    0,    0,    0,   48,    0,   11,
       30,   27,   15,    0,   16,    0,   14,   11,   11,   11,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   21,    0,   23,    0,    0,   37,   41,

        4,   12,    0,    0,    0,   13,   13,   45,    0,   13,
       11,    0,    9,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   22,    0,
        0,    0,   46,   13,   11,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   24,    0,   10,    0,    0,    0,
        0,    0,    2,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    3,    0,    0,    6,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    1,    2,    8,    0,    0,    6,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    7,    0,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    6,    1,    7,    1,
        1,    8,    1,    1,    9,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,   19,    1,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
        1,   21,    1,    1,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   10,   32,   33,   34,   35,
       36,   37,   10,   38,   39,   40,   41,   42,   10,   43,
       44,   10,   45,   46,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[48] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    4,
        1,    5,    5,    1,    1,    1,    1,    6,    1,    4,
        1,    4,    5,    5,    5,    5,    5,    5,    4,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[280] =
    {   0,
        0,  427,   43,   44,    0,    0,  424,  423,   45,   49,
       55,   56,   47,   48,  427,  426,  425,  424,  426,  434,
       66,   69,   71,   38,   75,    0,   73,   67,  434,  434,
      407,   86,  386,  434,  434,  111,  434,  418,    0,  414,
       83,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      413,  434,  412,  434,  434,  434,  434,  413,   83,   99,
      415,  434,  379,  434,  409,  408,  407,  434,  152,    0,
      434,  434,   93,  383,  434,  394,  434,    0,    0,  373,
      116,  383,  366,  377,   65,   29,  366,   84,  375,  365,
       85,  369,  398,  397,  394,  434,    0,  107,  434,  434,

      434,  434,  397,  372,  391,  434,  434,  434,  390,  389,
      359,  128,  434,  130,  357,  360,   65,  367,  357,  106,
      350,  351,  350,  358,  363,  353,  347,  352,  434,  335,
      356,  373,  434,  434,  341,  337,  346,  336,  348,  347,
      333,  363,  348,  343,  103,  346,  331,  328,  339,  335,
      326,  336,  335,  325,  313,    0,    0,  330,  323,  319,
      331,  346,  434,  317,  313,  343,  320,  327,  310,  307,
      320,  133,  306,  305,  309,  434,  308,  339,  434,  314,
      299,  299,  301,  314,  305,  298,  299,  295,  293,  291,
      321,  292,  291,  434,  144,  434,  288,  301,  316,  286,

      285,  286,  283,  293,  280,  282,  300,  279,  292,  291,
      273,  272,  271,  272,  282,  285,  272,  279,  266,  277,
      278,  297,  274,  253,  241,  245,  238,  219,  155,  163,
      155,  149,  158,  147,  179,  145,  143,  142,  155,  154,
      139,  143,  141,  165,  165,  144,  138,  136,  129,  128,
      117,  102,  434,  109,   97,   96,  106,  101,  434,  194,
      200,  206,  212,  218,  224,  230,  236,  242,  245,  121,
      247,  253,  259,  265,  271,  277,  283,  289,  295
    } ;

static const flex_int16_t yy_def[280] =
    {   0,
      259,    1,  260,  260,  260,  260,  261,  261,  262,  262,
      263,  263,  264,  264,  265,  265,  266,  266,  259,  259,
      259,  259,  267,  259,  268,  269,  259,  270,  259,  259,
      271,  269,   32,  259,  259,  259,  259,  272,  273,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  267,
      274,  259,  259,  259,  275,  275,  275,  259,  275,  269,
      259,  259,  270,  270,  259,  271,  259,   32,  269,  269,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  272,  272,  259,  259,  276,  259,  259,  259,

      259,  259,  274,  259,  277,  259,  259,  259,  277,  259,
      269,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  276,
      259,  277,  259,  259,  269,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  276,  278,  269,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  278,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  279,  259,  259,  259,  259,  259,
      259,  259,  259,  279,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,    0,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259
    } ;

static const flex_int16_t yy_nxt[482] =
    {   0,
       20,   21,   22,   21,   23,   24,   25,   20,   20,   26,
       27,   28,   28,   29,   30,   31,   20,   20,   20,   26,
       20,   26,   32,   32,   32,   32,   33,   32,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   34,   35,   20,   38,   38,   39,
       39,  119,   47,   40,   40,   48,   47,   53,   53,   48,
       50,   50,   41,   41,  120,   51,   51,   59,   59,   59,
       59,   59,   59,   61,   63,   62,   66,   67,   73,   73,
       71,   68,   64,   72,   59,   59,   59,   42,   42,   43,
       43,  117,  141,   54,   54,   69,   75,   78,   78,   97,

      118,   61,   98,  102,   73,   73,  122,  142,   78,   78,
       78,   78,   78,   78,  145,   79,   81,  112,  113,  112,
      126,  104,   75,   97,  123,   74,   98,  179,  127,  112,
      113,  112,  179,  179,  179,  167,   82,   83,   84,  168,
      146,  192,  179,   85,  207,   86,   87,   88,   89,   90,
       91,   92,  211,  136,  193,   64,  109,  137,  110,  207,
      258,  257,  256,  109,  255,  212,  254,  253,  138,  245,
      109,  252,  109,  251,  109,  109,  176,  250,  249,  109,
      248,  247,  246,  245,  179,  243,  109,  179,  179,  109,
      242,  109,  179,  109,   37,   37,   37,   37,   37,   37,

       44,   44,   44,   44,   44,   44,   46,   46,   46,   46,
       46,   46,   49,   49,   49,   49,   49,   49,   52,   52,
       52,   52,   52,   52,   55,   55,   55,   55,   55,   55,
       57,   57,   57,   57,   57,   57,   60,   60,   60,   60,
       60,   60,   65,   65,   65,   65,   65,   65,   70,   70,
       76,   76,   76,   93,  241,   93,   93,   93,   93,   95,
      240,   95,   95,   95,   95,  103,  103,  239,  103,  103,
      103,  105,  105,  105,  105,  105,  105,  130,  238,  130,
      130,  130,  130,  132,  132,  132,  132,  132,  132,  178,
      237,  178,  178,  178,  178,  244,  236,  244,  244,  244,

      244,  235,  163,  234,  179,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  179,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  176,  195,  194,  163,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  155,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  133,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      144,  143,  140,  139,  135,  106,  134,  133,  131,   61,

      129,   94,   94,  128,  125,  124,  121,  116,  115,  114,
      111,   77,   75,  108,  107,  106,  104,   61,  101,  100,
       99,   96,   94,   80,   77,  259,   58,   58,   56,   56,
       45,   45,   36,   19,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259
    } ;

static const flex_int16_t yy_chk[482] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    3,
        4,   86,    9,    3,    4,    9,   10,   13,   14,   10,
       11,   12,    3,    4,   86,   11,   12,   21,   21,   21,
       22,   22,   22,   23,   24,   23,   25,   25,   28,   28,
       27,   25,   24,   27,   59,   59,   59,    3,    4,    3,
        4,   85,  117,   13,   14,   25,   28,   32,   32,   41,

       85,   60,   41,   60,   73,   73,   88,  117,   32,   32,
       32,   32,   32,   32,  120,   32,   36,   81,   81,   81,
       91,   88,   73,   98,   88,  270,   98,  258,   91,  112,
      112,  112,  257,  256,  255,  145,   36,   36,   36,  145,
      120,  172,  254,   36,  252,   36,   36,   36,   36,   36,
       36,   36,  195,  114,  172,   36,   69,  114,   69,  251,
      250,  249,  248,   69,  247,  195,  246,  245,  114,  244,
       69,  243,   69,  242,   69,   69,  241,  240,  239,   69,
      238,  237,  236,  235,  234,  233,   69,  232,  231,   69,
      230,   69,  229,   69,  260,  260,  260,  260,  260,  260,

      261,  261,  261,  261,  261,  261,  262,  262,  262,  262,
      262,  262,  263,  263,  263,  263,  263,  263,  264,  264,
      264,  264,  264,  264,  265,  265,  265,  265,  265,  265,
      266,  266,  266,  266,  266,  266,  267,  267,  267,  267,
      267,  267,  268,  268,  268,  268,  268,  268,  269,  269,
      271,  271,  271,  272,  228,  272,  272,  272,  272,  273,
      227,  273,  273,  273,  273,  274,  274,  226,  274,  274,
      274,  275,  275,  275,  275,  275,  275,  276,  225,  276,
      276,  276,  276,  277,  277,  277,  277,  277,  277,  278,
      224,  278,  278,  278,  278,  279,  223,  279,  279,  279,

      279,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  178,  177,  175,  174,  173,  171,  170,  169,  168,
      167,  166,  165,  164,  162,  161,  160,  159,  158,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  132,
      131,  130,  128,  127,  126,  125,  124,  123,  122,  121,
      119,  118,  116,  115,  111,  110,  109,  105,  104,  103,

       95,   94,   93,   92,   90,   89,   87,   84,   83,   82,
       80,   76,   74,   67,   66,   65,   63,   61,   58,   53,
       51,   40,   38,   33,   31,   19,   18,   17,   16,   15,
        8,    7,    2,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[51] =
    {   0,
0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 
    1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "metagrammar.lex"
/*
metagrammar.lex -- flex scanner for bison metagrammar
Copyright 2005 Alfonso Tarantini
This file is part of Forson.

Forson is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

Forson is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Forson; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
#line 23 "metagrammar.lex"

/*-----------------------------------------------*/
/*FLEX G_SCANNER DEFINITION FOR BISON METAGRAMMAR*/
/*-----------------------------------------------*/

#include <metagrammar.tab.h>
#include <generation.h>

/*SHORTHAND MACROS*/
#define MESSAGE_WITH(M) fprintf(message_stream, "%s: line %d: %s: %s\n",input_grammar_file_path,yylineno,M, yytext)
#define MESSAGE_WITHOUT(M) fprintf(message_stream, "%s: line %d: %s\n",input_grammar_file_path,yylineno,M)
#define ERROR(M) error(BAD_INPUT,0,"%s: line %d: %s: %s",input_grammar_file_path,yylineno,M,yytext)
#define remove_quotes(M) M+=sizeof(char);M[yyleng-2]='\0'; yyleng-=2

/*GLOBALS DEFINED IN CALLING FUNCTION*/

/*NAME OF THE INPUT FILE, FOR ERROR REPORTING PURPOSES*/
extern char *input_grammar_file_path;
/*SLE IN WHICH TO INSERT THE SYMBOLS FOUND DURING SCAN*/
extern symbol_list_entry *symbol_table;
/*GLOBAL STREAM FOR MESSAGES*/
extern FILE *message_stream;


/*WORKING VARIABLES*/

/*FOR NOT BEING FOOLED BY NESTED BRACKETS*/
int brack_nesting = 0, prologue = 0;

#line 712 "metagrammar.yylex.c"

#line 714 "metagrammar.yylex.c"

#define INITIAL 0
#define in_curly_brackets 1
#define in_double_quotes 2
#define in_comment 3
#define exiting_comment 4
#define in_prologue 5
#define exiting_prologue 6
#define in_inline_comment 7
#define in_misc_decl 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 73 "metagrammar.lex"



#line 946 "metagrammar.yylex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 434 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("found START_DECL");
				return START_DECL;
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 82 "metagrammar.lex"
{
				/*THESE BISON DECLARATIONS ARE ALL EQUAL TO */
				/*THE %token DECLARATION                    */
				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found TOKEN_DECL");
				return TOKEN_DECL;
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 90 "metagrammar.lex"
{
				/*THESE DECLARATIONS DON'T MATTER TO FORSON     */
				/*BUT IDENTIFIERS CAN FOLLOW (MUST BE DISCARDED)*/
				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found MISCELLANEOUS_DECL, entering start condition");
				BEGIN(in_misc_decl);
			}
	YY_BREAK
case 4:
/* rule 4 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 98 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("...exiting start condition");
				yylineno--;
				yyless(0);
				BEGIN(0);
				return MISCELLANEOUS_DECL;
			}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 107 "metagrammar.lex"
{
				/*EAT ANYTHING IN MISCELLANEOUS DECLARATIONS*/
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 111 "metagrammar.lex"
{
				/*THESE DECLARATIONS DON'T MATTER TO FORSON*/
				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found MISCELLANEOUS_EMPTY_DECL");
				return MISCELLANEOUS_EMPTY_DECL;
			}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 118 "metagrammar.lex"
{
				/*THESE DECLARATIONS DON'T MATTER BUT SPECIFY A STRING (MUST BE DISCARDED)*/
				/*REMOVE TRAILING NEWLINE*/
				yytext[yyleng-2] = '\0';
				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found MISCELLANEOUS_FILENAME_DECL");
				return MISCELLANEOUS_FILENAME_DECL;
			}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 127 "metagrammar.lex"
{
				/*MYSTERIOUS UNDOCUMENTED DECLARATION         */
				/*WHICH APPEARS IN RULES!!!                   */
				/*FOUND IN PARSERS FOR THE gcc                */
				/*LOOKS LIKE PRECEDENCE SO FORSON DOESN'T CARE*/
			}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 134 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("found PART_SEPARATOR");
				return PART_SEPARATOR;
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 140 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("found ERROR_RESERVED_TOKEN");

				yylval = -1;

				return ERROR_RESERVED_TOKEN;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 149 "metagrammar.lex"
{
				symbol_list_entry *s = NULL;

				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found IDENTIFIER");

				/*ADD THE NEW IDENTIFIER IF MISSING. SET SEMANTIC VALUES*/
				s = get_symbol_by_name(symbol_table, yytext);
					
				if(s == NULL)
				{
					yylval = (int) insert_symbol(symbol_table, yytext, UNDEFINED);
				}
				else if(is_LITERAL(s) == 1)
				{
					yylval = (int) insert_symbol(symbol_table, yytext, UNDEFINED);
				}
				else
				{
					yylval = (int) s->id;
				}
				
				return IDENTIFIER;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 174 "metagrammar.lex"
{
				symbol_list_entry *s = NULL;

				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found DOUBLE_QUOTED_LITERAL");

				remove_quotes(yytext);
				/*ADD THE NEW LITERAL IF MISSING. SET SEMANTIC VALUE*/
				s = get_symbol_by_name(symbol_table, yytext);
				if(s == NULL)
				{
					yylval = (int) insert_symbol(symbol_table, yytext, LITERAL);
				}
				else if(is_LITERAL(s) == 0)
				{
					yylval = (int) insert_symbol(symbol_table, yytext, LITERAL);
				}
				else
				{
					yylval = (int) s->id;
				}

				return DOUBLE_QUOTED_LITERAL;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 199 "metagrammar.lex"
{
				symbol_list_entry *s = NULL;

				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found SINGLE_QUOTED_LITERAL");

				remove_quotes(yytext);	

				/*ADD THE NEW LITERAL IF MISSING. SET SEMANTIC VALUE*/
				s = get_symbol_by_name(symbol_table, yytext);
				if(s == NULL)
				{
					yylval = (int) insert_symbol(symbol_table, yytext, LITERAL);
				}
				else if(is_LITERAL(s) == 0)
				{
					yylval = (int) insert_symbol(symbol_table, yytext, LITERAL);
				}
				else
				{
					yylval = (int) s->id;
				}

				return SINGLE_QUOTED_LITERAL;
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 225 "metagrammar.lex"
{
				/*EAT SEMANTIC VALUE TYPE IDENTIFIERS (FOUND IN TOKEN DECLARATIONS)*/
				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found SEMANTIC VALUE TYPE IDENTIFIER");
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 231 "metagrammar.lex"
{
				/*EAT DECIMAL AND HEX NUMBERS*/
				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found NUMBER");
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 237 "metagrammar.lex"
{
				/*EAT DECIMAL AND HEX NUMBERS*/
				if(must_print_message(G_SCANNER))
					MESSAGE_WITH("found HEX_NUMBER");
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 243 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("found SEMICOLON");
				return (unsigned char)';';
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 249 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("found COLON");
				return (unsigned char)':';
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 255 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("found VERTICAL_BAR");
				return (unsigned char)'|';
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 261 "metagrammar.lex"
{
				brack_nesting++;
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("entering BRACKETS...");
				BEGIN(in_curly_brackets);
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 268 "metagrammar.lex"
/*JUST EAT THIS TO AVOID TO CONSIDER QUOTED BRACKETS*/
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 270 "metagrammar.lex"
/*JUST EAT THIS TO AVOID TO CONSIDER QUOTED BRACKETS*/
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 272 "metagrammar.lex"
{
				/*TO AVOID CONSIDERING BRACKETS IN COMMENTS*/
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("entering COMMENT in BRACKETS...");
				BEGIN(in_comment);
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 278 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT(yytext);
                brack_nesting--;
                BEGIN(0);
                return SET_SYM_VAL; 
    } 	/*EAT ANYTHING IN CURLY BRACKETS EXCEPT BRACKETS*/
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 286 "metagrammar.lex"
{
				brack_nesting++;
			}
	YY_BREAK
case YY_STATE_EOF(in_curly_brackets):
#line 289 "metagrammar.lex"
{
				strcpy(yytext, "EOF");
				ERROR("expecting }, found");
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 293 "metagrammar.lex"
{
				brack_nesting--;			
				if(brack_nesting == 0)
				{
					if(must_print_message(G_SCANNER))
						MESSAGE_WITHOUT("exiting BRACKETS");
					BEGIN(0);
				}
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 303 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("in INLINE COMMENT...");
				BEGIN(in_inline_comment);
			}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 308 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("out OF INLINE COMMENT");
				BEGIN(0);
			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 313 "metagrammar.lex"
/*EAT EVERYTHING ELSE*/
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 315 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("entering COMMENT...");
				BEGIN(in_comment);
			}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 321 "metagrammar.lex"
/*EAT ANYTHING IN COMMENT EXCEPT '*' */
	YY_BREAK
case YY_STATE_EOF(in_comment):
#line 323 "metagrammar.lex"
{
				strcpy(yytext, "EOF");
				ERROR("expecting */, found");
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 328 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("exiting COMMENT...");
				BEGIN(exiting_comment);
			}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 334 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("back in COMMENT...");
				BEGIN(in_comment);
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 340 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("exiting COMMENT...");
			}
	YY_BREAK
case YY_STATE_EOF(exiting_comment):
#line 345 "metagrammar.lex"
{
				strcpy(yytext, "EOF");
				yyleng = 4;
				ERROR("expecting */, found");
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 351 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("out of COMMENT");
				/*IF COMMENT WAS IN BRACKETS WE CAN'T */
				/*GET BACK TO INITIAL STATE (0)       */
				if(brack_nesting != 0)
				{
					BEGIN(in_curly_brackets);
				}
				else if(prologue != 0)
				{
					BEGIN(in_prologue);
				}
				else
				{
					BEGIN(0);
				}
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 370 "metagrammar.lex"
{
				prologue++;
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("in PROLOGUE...");
				BEGIN(in_prologue);
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 377 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("entering COMMENT in PROLOGUE...");
				BEGIN(in_comment);
			}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 382 "metagrammar.lex"
/*EAT ANYTHING IN PROLOGUE EXCEPT '%' */	
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 384 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("exiting PROLOGUE...");
				BEGIN(exiting_prologue);
			}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 390 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("back in PROLOGUE...");
				BEGIN(in_prologue);
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 395 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("entering COMMENT in PROLOGUE...");
				BEGIN(in_comment);
			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 400 "metagrammar.lex"
{
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("out of PROLOGUE");
				prologue--;
				BEGIN(0);
			}
	YY_BREAK
case YY_STATE_EOF(exiting_prologue):
#line 406 "metagrammar.lex"
{
				strcpy(yytext, "EOF");
				yyleng = 4;
				ERROR("expecting *}, found");
			}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 412 "metagrammar.lex"
/*EAT WHITESPACE*/
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 414 "metagrammar.lex"
{
				strcpy(yytext, "new line");
				ERROR("expecting \", found");
			}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 418 "metagrammar.lex"
{
				strcpy(yytext, "tab or newline");
				ERROR("expecting character, found");
			}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 423 "metagrammar.lex"
{
				ERROR("found multi-character character literal");
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 427 "metagrammar.lex"
{
				ERROR("found empty string literal");
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 431 "metagrammar.lex"
{
				ERROR("found empty character literal");
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 435 "metagrammar.lex"
{
				ERROR("unrecognized character");
			}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(in_double_quotes):
case YY_STATE_EOF(in_prologue):
case YY_STATE_EOF(in_inline_comment):
case YY_STATE_EOF(in_misc_decl):
#line 439 "metagrammar.lex"
{
				strcpy(yytext, "EOF");
				if(must_print_message(G_SCANNER))
					MESSAGE_WITHOUT("Reached EOF");
				return 0;
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 446 "metagrammar.lex"
ECHO;
	YY_BREAK
#line 1578 "metagrammar.yylex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 259);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 446 "metagrammar.lex"


